# Generated by Django 2.0.13 on 2020-09-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoCollectionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeInfoDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('rowid', models.CharField(default='', max_length=10)),
                ('c2', models.CharField(default='', max_length=20)),
                ('c3', models.CharField(default='', max_length=50)),
                ('c4', models.CharField(default='', max_length=50)),
                ('c5', models.CharField(default='', max_length=20)),
                ('c6', models.CharField(default='', max_length=8)),
            ],
        ),
    ]
