# Generated by Django 2.0.13 on 2020-10-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoCollectionApp', '0002_officeinfodb'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeinfodb',
            name='date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
