# Generated by Django 2.0.13 on 2020-11-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoCollectionApp', '0003_officeinfodb_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomInfoDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('title', models.CharField(default='', max_length=50)),
                ('content', models.CharField(default='', max_length=1000)),
                ('date', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
