# Generated by Django 2.0.13 on 2020-12-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoCollectionApp', '0004_custominfodb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfodb',
            name='mailaddr',
            field=models.CharField(default='', max_length=30),
        ),
    ]
