# Generated by Django 2.0.13 on 2021-07-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoCollectionApp', '0005_auto_20201202_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeinfodb',
            name='c6',
            field=models.CharField(default='', max_length=50),
        ),
    ]
