# Generated by Django 2.0.13 on 2020-11-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindb',
            name='mail',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='logindb',
            name='profilesetting',
            field=models.CharField(default='0', max_length=8),
        ),
    ]
