# Generated by Django 2.0.13 on 2020-12-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0002_auto_20201120_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindb',
            name='mail',
            field=models.CharField(default='', max_length=30),
        ),
    ]
