# Generated by Django 2.0.13 on 2020-09-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesInfoDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=40)),
                ('content', models.CharField(default='', max_length=5000)),
                ('date', models.CharField(default='', max_length=20)),
                ('author', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
