# Generated by Django 2.0.13 on 2020-09-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesinfodb',
            name='contentid',
            field=models.CharField(default='', max_length=10),
        ),
    ]
