# Generated by Django 2.0.13 on 2020-09-12 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_articlesinfodb_contentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlesinfodb',
            name='contentid',
        ),
    ]
