# Generated by Django 2.0.13 on 2020-09-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_remove_articlesinfodb_contentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesinfodb',
            name='author',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='articlesinfodb',
            name='content',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='articlesinfodb',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
